name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure gcloud and verify authentication
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config list
          gcloud auth list
      
      - name: Copy files to GCP VM
        run: |
          # Create SSH directory and accept prompts automatically
          mkdir -p ~/.ssh
          echo "y" | gcloud compute scp --recurse ./ \
            tanmaymi251@ubuntu-4gb:~/test \
            --zone=us-central1-c \
            --ssh-key-expire-after=1h