name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check secrets (REMOVE AFTER TESTING)
        run: |
          if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "❌ GCP_PROJECT_ID secret is empty"
          else
            echo "✅ GCP_PROJECT_ID is set"
          fi
          
          if [ -z "${{ secrets.SERVICE_ACCOUNT_KEY }}" ]; then
            echo "❌ SERVICE_ACCOUNT_KEY secret is empty"
          else
            echo "✅ SERVICE_ACCOUNT_KEY is set (length: ${#SERVICE_KEY})"
          fi
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Verify gcloud configuration
        run: |
          gcloud config list
          gcloud auth list
      
      - name: Copy files to GCP VM
        run: |
          # Accept SSH key generation automatically
          yes | gcloud compute scp --recurse ./ \
            tanmaymi251@ubuntu-4gb:~/test \
            --zone=us-central1-c
            