name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' | base64 -d > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          rm /tmp/gcp-key.json
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Verify gcloud configuration
        run: |
          gcloud config list
          gcloud auth list
      
      - name: Copy files to GCP VM
        run: |
          # Accept SSH key generation automatically
          yes | gcloud compute scp --recurse ./ \
            tanmaymi251@ubuntu-4gb:~/test \
            --zone=us-central1-c