name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Verify gcloud configuration
        run: |
          gcloud config list
          gcloud auth list
      
      - name: Copy files to GCP VM
        run: |
          # Accept SSH key generation automatically
          yes | gcloud compute scp --recurse ./ \
            tanmaymi251@ubuntu-4gb:~/test \
            --zone=us-central1-c